<?php

declare(strict_types=1);

namespace App\Support;

final class Translator
{
    private static array $messages = [
        'en' => [
            'site.title' => 'Arcvis',
            'site.tagline' => 'Monochrome archive for essays, notes, and selected works.',
            'nav.home' => 'Home',
            'nav.blog' => 'Blog',
            'nav.works' => 'Works',
            'nav.admin' => 'Admin',
            'nav.install' => 'Install',
            'hero.heading' => 'Retro terminal CMS',
            'hero.copy' => 'A quiet black-and-white publishing system with a typewriter soul.',
            'section.posts' => 'Latest posts',
            'section.works' => 'Selected works',
            'section.system' => 'System status',
            'section.back' => 'Return',
            'label.read_more' => 'Read entry',
            'label.visit' => 'Visit link',
            'label.locale' => 'Language',
            'label.username' => 'Username',
            'label.password' => 'Password',
            'label.display_name' => 'Display name',
            'label.site_name' => 'Site name',
            'label.tagline' => 'Tagline',
            'label.db_host' => 'DB host',
            'label.db_port' => 'DB port',
            'label.db_name' => 'DB name',
            'label.db_user' => 'DB user',
            'label.db_pass' => 'DB password',
            'label.default_locale' => 'Default locale',
            'label.title' => 'Title',
            'label.slug' => 'Slug',
            'label.excerpt' => 'Excerpt',
            'label.body' => 'Body',
            'label.status' => 'Status',
            'label.url' => 'URL',
            'label.description' => 'Description',
            'label.sort_order' => 'Sort order',
            'label.actions' => 'Actions',
            'button.save' => 'Save',
            'button.login' => 'Login',
            'button.install' => 'Install system',
            'button.create_post' => 'Create post',
            'button.create_work' => 'Create work',
            'button.logout' => 'Logout',
            'button.edit' => 'Edit',
            'button.delete' => 'Delete',
            'button.back_blog' => 'Back to blog',
            'button.back_admin' => 'Back to admin',
            'status.installed' => 'Installed',
            'status.not_installed' => 'Not installed',
            'status.published' => 'Published',
            'status.draft' => 'Draft',
            'install.heading' => 'Installer',
            'install.copy' => 'Bootstrap the database, save config, and create the first administrator.',
            'install.done' => 'Installation complete. You can now sign in.',
            'install.already' => 'The system is already installed. Remove storage/config.php only if you really need to reinstall.',
            'install.password_hint' => 'Administrator password must be at least 8 characters.',
            'admin.heading' => 'Admin console',
            'admin.posts' => 'Posts',
            'admin.works' => 'Works',
            'admin.settings' => 'Settings',
            'admin.welcome' => 'Welcome back, :name.',
            'admin.saved' => 'Saved successfully.',
            'admin.deleted' => 'Deleted successfully.',
            'admin.login_failed' => 'Invalid credentials.',
            'empty.posts' => 'No published posts yet.',
            'empty.works' => 'No visible works yet.',
            'empty.table' => 'No records yet.',
            'post.not_found' => 'Post not found.',
            'confirm.delete' => 'Delete this record?',
        ],
        'zh-CN' => [
            'site.title' => 'Arcvis',
            'site.tagline' => '黑白档案库，用于文章、笔记与作品展示。',
            'nav.home' => '首页',
            'nav.blog' => '博客',
            'nav.works' => '作品',
            'nav.admin' => '后台',
            'nav.install' => '安装',
            'hero.heading' => '复古终端 CMS',
            'hero.copy' => '一个安静的黑白发布系统，保留打字机般的节奏。',
            'section.posts' => '最新文章',
            'section.works' => '精选作品',
            'section.system' => '系统状态',
            'section.back' => '返回',
            'label.read_more' => '阅读条目',
            'label.visit' => '访问链接',
            'label.locale' => '语言',
            'label.username' => '用户名',
            'label.password' => '密码',
            'label.display_name' => '显示名称',
            'label.site_name' => '网站名称',
            'label.tagline' => '副标题',
            'label.db_host' => '数据库主机',
            'label.db_port' => '数据库端口',
            'label.db_name' => '数据库名',
            'label.db_user' => '数据库用户',
            'label.db_pass' => '数据库密码',
            'label.default_locale' => '默认语言',
            'label.title' => '标题',
            'label.slug' => 'Slug',
            'label.excerpt' => '摘要',
            'label.body' => '正文',
            'label.status' => '状态',
            'label.url' => '链接',
            'label.description' => '介绍',
            'label.sort_order' => '排序',
            'label.actions' => '操作',
            'button.save' => '保存',
            'button.login' => '登录',
            'button.install' => '安装系统',
            'button.create_post' => '新建文章',
            'button.create_work' => '新建作品',
            'button.logout' => '退出登录',
            'button.edit' => '编辑',
            'button.delete' => '删除',
            'button.back_blog' => '返回博客',
            'button.back_admin' => '返回后台',
            'status.installed' => '已安装',
            'status.not_installed' => '未安装',
            'status.published' => '已发布',
            'status.draft' => '草稿',
            'install.heading' => '安装程序',
            'install.copy' => '初始化数据库、写入配置，并创建首个管理员账号。',
            'install.done' => '安装完成，现在可以登录后台。',
            'install.already' => '系统已经安装。如确需重装，请先手动删除 storage/config.php。',
            'install.password_hint' => '管理员密码至少需要 8 位。',
            'admin.heading' => '管理终端',
            'admin.posts' => '文章',
            'admin.works' => '作品',
            'admin.settings' => '设置',
            'admin.welcome' => '欢迎回来，:name。',
            'admin.saved' => '保存成功。',
            'admin.deleted' => '删除成功。',
            'admin.login_failed' => '用户名或密码错误。',
            'empty.posts' => '还没有已发布文章。',
            'empty.works' => '还没有可展示作品。',
            'empty.table' => '还没有记录。',
            'post.not_found' => '文章不存在。',
            'confirm.delete' => '确定删除这条记录吗？',
        ],
    ];

    public static function get(string $key, array $replace = [], string $locale = 'en'): string
    {
        $line = self::$messages[$locale][$key] ?? self::$messages['en'][$key] ?? $key;

        foreach ($replace as $name => $value) {
            $line = str_replace(':' . $name, (string) $value, $line);
        }

        return $line;
    }
}
